version: '3.1'
services:
  mysql-server:
    image: mysql:latest
    # change me 
    container_name: my-server
    command: --default-authentication-plugin=mysql_native_password
    # volumes:
    #  - ./data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker # User: root
    ports:
    # change me 
     - 3309:3306
networks:
  default:
    external:
    # Change me
      name: ga-te

# CLI Access:
# docker-compose run --rm mysql-server mysql -h mysql-server -u root -p